<?php

namespace Database\Seeders;

use App\Models\CountryFlag;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountryFlagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afghanistan', 'flag' => 'https://www.worldometers.info/img/flags/af-flag.gif'],
            ['country_name' => 'Albania', 'flag' => 'https://www.worldometers.info/img/flags/al-flag.gif'],
            ['country_name' => 'Algeria', 'flag' => 'https://www.worldometers.info/img/flags/ag-flag.gif'],
            ['country_name' => 'Andorra', 'flag' => 'https://www.worldometers.info/img/flags/an-flag.gif'],
            ['country_name' => 'Angola', 'flag' => 'https://www.worldometers.info/img/flags/ao-flag.gif'],
            ['country_name' => 'Argentina', 'flag' => 'https://www.worldometers.info/img/flags/ar-flag.gif'],
            ['country_name' => 'Armenia', 'flag' => 'https://www.worldometers.info/img/flags/am-flag.gif'],
            ['country_name' => 'Australia', 'flag' => 'https://www.worldometers.info/img/flags/as-flag.gif'],
            ['country_name' => 'Austria', 'flag' => 'https://www.worldometers.info/img/flags/au-flag.gif'],
            ['country_name' => 'Azerbaijan', 'flag' => 'https://www.worldometers.info/img/flags/aj-flag.gif'],
            ['country_name' => 'Bahamas', 'flag' => 'https://www.worldometers.info/img/flags/bf-flag.gif'],
            ['country_name' => 'Bahrain', 'flag' => 'https://www.worldometers.info/img/flags/ba-flag.gif'],
            ['country_name' => 'Bangladesh', 'flag' => 'https://www.worldometers.info/img/flags/bg-flag.gif'],
            ['country_name' => 'Barbados', 'flag' => 'https://www.worldometers.info/img/flags/bb-flag.gif'],
            ['country_name' => 'Belarus', 'flag' => 'https://www.worldometers.info/img/flags/bo-flag.gif'],
            ['country_name' => 'Belgium', 'flag' => 'https://www.worldometers.info/img/flags/be-flag.gif'],
            ['country_name' => 'Belize', 'flag' => 'https://www.worldometers.info/img/flags/bh-flag.gif'],
            ['country_name' => 'Benin', 'flag' => 'https://www.worldometers.info/img/flags/bn-flag.gif'],
            ['country_name' => 'Bhutan', 'flag' => 'https://www.worldometers.info/img/flags/bt-flag.gif'],
            ['country_name' => 'Bolivia', 'flag' => 'https://www.worldometers.info/img/flags/bl-flag.gif'],
            ['country_name' => 'Botswana', 'flag' => 'https://www.worldometers.info/img/flags/bc-flag.gif'],
            ['country_name' => 'Brazil', 'flag' => 'https://www.worldometers.info/img/flags/br-flag.gif'],
            ['country_name' => 'Brunei', 'flag' => 'https://www.worldometers.info/img/flags/bx-flag.gif'],
            ['country_name' => 'Bulgaria', 'flag' => 'https://www.worldometers.info/img/flags/bu-flag.gif'],
            ['country_name' => 'Burkina Faso', 'flag' => 'https://www.worldometers.info/img/flags/uv-flag.gif'],
            ['country_name' => 'Burundi', 'flag' => 'https://www.worldometers.info/img/flags/by-flag.gif'],
            ['country_name' => 'Cabo Verde', 'flag' => 'https://www.worldometers.info/img/flags/cv-flag.gif'],
            ['country_name' => 'Cambodia', 'flag' => 'https://www.worldometers.info/img/flags/cb-flag.gif'],
            ['country_name' => 'Cameroon', 'flag' => 'https://www.worldometers.info/img/flags/cm-flag.gif'],
            ['country_name' => 'Canada', 'flag' => 'https://www.worldometers.info/img/flags/ca-flag.gif'],
            ['country_name' => 'CAR', 'flag' => 'https://www.worldometers.info/img/flags/ct-flag.gif'],
            ['country_name' => 'Chad', 'flag' => 'https://www.worldometers.info/img/flags/cd-flag.gif'],
            ['country_name' => 'Chile', 'flag' => 'https://www.worldometers.info/img/flags/ci-flag.gif'],
            ['country_name' => 'China', 'flag' => 'https://www.worldometers.info/img/flags/ch-flag.gif'],
            ['country_name' => 'Colombia', 'flag' => 'https://www.worldometers.info/img/flags/co-flag.gif'],
            ['country_name' => 'Comoros', 'flag' => 'https://www.worldometers.info/img/flags/cn-flag.gif'],
            ['country_name' => 'Congo', 'flag' => 'https://www.worldometers.info/img/flags/cg-flag.gif'],
            ['country_name' => 'Costa Rica', 'flag' => 'https://www.worldometers.info/img/flags/cs-flag.gif'],
            ['country_name' => 'Croatia', 'flag' => 'https://www.worldometers.info/img/flags/hr-flag.gif'],
            ['country_name' => 'Cuba', 'flag' => 'https://www.worldometers.info/img/flags/cu-flag.gif'],
            ['country_name' => 'Cyprus', 'flag' => 'https://www.worldometers.info/img/flags/cy-flag.gif'],
            ['country_name' => 'Czechia', 'flag' => 'https://www.worldometers.info/img/flags/ez-flag.gif'],
            ['country_name' => 'Denmark', 'flag' => 'https://www.worldometers.info/img/flags/da-flag.gif'],
            ['country_name' => 'Djibouti', 'flag' => 'https://www.worldometers.info/img/flags/dj-flag.gif'],
            ['country_name' => 'Dominica', 'flag' => 'https://www.worldometers.info/img/flags/do-flag.gif'],
            ['country_name' => 'Dominican Republic', 'flag' => 'https://www.worldometers.info/img/flags/dr-flag.gif'],
            ['country_name' => 'Ecuador', 'flag' => 'https://www.worldometers.info/img/flags/ec-flag.gif'],
            ['country_name' => 'Egypt', 'flag' => 'https://www.worldometers.info/img/flags/eg-flag.gif'],
            ['country_name' => 'El Salvador', 'flag' => 'https://www.worldometers.info/img/flags/es-flag.gif'],
            ['country_name' => 'Equatorial Guinea', 'flag' => 'https://www.worldometers.info/img/flags/ek-flag.gif'],
            ['country_name' => 'Eritrea', 'flag' => 'https://www.worldometers.info/img/flags/er-flag.gif'],
            ['country_name' => 'Estonia', 'flag' => 'https://www.worldometers.info/img/flags/en-flag.gif'],
            ['country_name' => 'Eswatini', 'flag' => 'https://www.worldometers.info/img/flags/wz-flag.gif'],
            ['country_name' => 'Ethiopia', 'flag' => 'https://www.worldometers.info/img/flags/et-flag.gif'],
            ['country_name' => 'Fiji', 'flag' => 'https://www.worldometers.info/img/flags/fj-flag.gif'],
            ['country_name' => 'Finland', 'flag' => 'https://www.worldometers.info/img/flags/fi-flag.gif'],
            ['country_name' => 'France', 'flag' => 'https://www.worldometers.info/img/flags/fr-flag.gif'],
            ['country_name' => 'Gabon', 'flag' => 'https://www.worldometers.info/img/flags/gb-flag.gif'],
            ['country_name' => 'Gambia', 'flag' => 'https://www.worldometers.info/img/flags/ga-flag.gif'],
            ['country_name' => 'Georgia', 'flag' => 'https://www.worldometers.info/img/flags/gg-flag.gif'],
            ['country_name' => 'Germany', 'flag' => 'https://www.worldometers.info/img/flags/gm-flag.gif'],
            ['country_name' => 'Ghana', 'flag' => 'https://www.worldometers.info/img/flags/gh-flag.gif'],
            ['country_name' => 'Greece', 'flag' => 'https://www.worldometers.info/img/flags/gr-flag.gif'],
            ['country_name' => 'Grenada', 'flag' => 'https://www.worldometers.info/img/flags/gj-flag.gif'],
            ['country_name' => 'Guatemala', 'flag' => 'https://www.worldometers.info/img/flags/gt-flag.gif'],
            ['country_name' => 'Guinea', 'flag' => 'https://www.worldometers.info/img/flags/gv-flag.gif'],
            ['country_name' => 'Guinea-Bissau', 'flag' => 'https://www.worldometers.info/img/flags/pu-flag.gif'],
            ['country_name' => 'Guyana', 'flag' => 'https://www.worldometers.info/img/flags/gy-flag.gif'],
            ['country_name' => 'Haiti', 'flag' => 'https://www.worldometers.info/img/flags/ha-flag.gif'],
            ['country_name' => 'Holy See', 'flag' => 'https://www.worldometers.info/img/flags/vt-flag.gif'],
            ['country_name' => 'Honduras', 'flag' => 'https://www.worldometers.info/img/flags/ho-flag.gif'],
            ['country_name' => 'Hungary', 'flag' => 'https://www.worldometers.info/img/flags/hu-flag.gif'],
            ['country_name' => 'Iceland', 'flag' => 'https://www.worldometers.info/img/flags/ic-flag.gif'],
            ['country_name' => 'India', 'flag' => 'https://www.worldometers.info/img/flags/in-flag.gif'],
            ['country_name' => 'Indonesia', 'flag' => 'https://www.worldometers.info/img/flags/id-flag.gif'],
            ['country_name' => 'Iran', 'flag' => 'https://www.worldometers.info/img/flags/ir-flag.gif'],
            ['country_name' => 'Iraq', 'flag' => 'https://www.worldometers.info/img/flags/iz-flag.gif'],
            ['country_name' => 'Ireland', 'flag' => 'https://www.worldometers.info/img/flags/ei-flag.gif'],
            ['country_name' => 'Israel', 'flag' => 'https://www.worldometers.info/img/flags/is-flag.gif'],
            ['country_name' => 'Italy', 'flag' => 'https://www.worldometers.info/img/flags/it-flag.gif'],
            ['country_name' => 'Jamaica', 'flag' => 'https://www.worldometers.info/img/flags/jm-flag.gif'],
            ['country_name' => 'Japan', 'flag' => 'https://www.worldometers.info/img/flags/ja-flag.gif'],
            ['country_name' => 'Jordan', 'flag' => 'https://www.worldometers.info/img/flags/jo-flag.gif'],
            ['country_name' => 'Kazakhstan', 'flag' => 'https://www.worldometers.info/img/flags/kz-flag.gif'],
            ['country_name' => 'Kenya', 'flag' => 'https://www.worldometers.info/img/flags/ke-flag.gif'],
            ['country_name' => 'Kiribati', 'flag' => 'https://www.worldometers.info/img/flags/kr-flag.gif'],
            ['country_name' => 'Kuwait', 'flag' => 'https://www.worldometers.info/img/flags/ku-flag.gif'],
            ['country_name' => 'Kyrgyzstan', 'flag' => 'https://www.worldometers.info/img/flags/kg-flag.gif'],
            ['country_name' => 'Laos', 'flag' => 'https://www.worldometers.info/img/flags/la-flag.gif'],
            ['country_name' => 'Latvia', 'flag' => 'https://www.worldometers.info/img/flags/lg-flag.gif'],
            ['country_name' => 'Lebanon', 'flag' => 'https://www.worldometers.info/img/flags/le-flag.gif'],
            ['country_name' => 'Lesotho', 'flag' => 'https://www.worldometers.info/img/flags/lt-flag.gif'],
            ['country_name' => 'Liberia', 'flag' => 'https://www.worldometers.info/img/flags/li-flag.gif'],
            ['country_name' => 'Libya', 'flag' => 'https://www.worldometers.info/img/flags/ly-flag.gif'],
            ['country_name' => 'Liechtenstein', 'flag' => 'https://www.worldometers.info/img/flags/ls-flag.gif'],
            ['country_name' => 'Lithuania', 'flag' => 'https://www.worldometers.info/img/flags/lh-flag.gif'],
            ['country_name' => 'Luxembourg', 'flag' => 'https://www.worldometers.info/img/flags/lu-flag.gif'],
            ['country_name' => 'Madagascar', 'flag' => 'https://www.worldometers.info/img/flags/ma-flag.gif'],
            ['country_name' => 'Malawi', 'flag' => 'https://www.worldometers.info/img/flags/mi-flag.gif'],
            ['country_name' => 'Malaysia', 'flag' => 'https://www.worldometers.info/img/flags/my-flag.gif'],
            ['country_name' => 'Maldives', 'flag' => 'https://www.worldometers.info/img/flags/mv-flag.gif'],
            ['country_name' => 'Mali', 'flag' => 'https://www.worldometers.info/img/flags/ml-flag.gif'],
            ['country_name' => 'Malta', 'flag' => 'https://www.worldometers.info/img/flags/mt-flag.gif'],
            ['country_name' => 'Marshall Islands', 'flag' => 'https://www.worldometers.info/img/flags/rm-flag.gif'],
            ['country_name' => 'Mauritania', 'flag' => 'https://www.worldometers.info/img/flags/mr-flag.gif'],
            ['country_name' => 'Mauritius', 'flag' => 'https://www.worldometers.info/img/flags/mp-flag.gif'],
            ['country_name' => 'Mexico', 'flag' => 'https://www.worldometers.info/img/flags/mx-flag.gif'],
            ['country_name' => 'Micronesia', 'flag' => 'https://www.worldometers.info/img/flags/fm-flag.gif'],
            ['country_name' => 'Moldova', 'flag' => 'https://www.worldometers.info/img/flags/md-flag.gif'],
            ['country_name' => 'Monaco', 'flag' => 'https://www.worldometers.info/img/flags/mn-flag.gif'],
            ['country_name' => 'Mongolia', 'flag' => 'https://www.worldometers.info/img/flags/mg-flag.gif'],
            ['country_name' => 'Montenegro', 'flag' => 'https://www.worldometers.info/img/flags/mj-flag.gif'],
            ['country_name' => 'Morocco', 'flag' => 'https://www.worldometers.info/img/flags/mo-flag.gif'],
            ['country_name' => 'Mozambique', 'flag' => 'https://www.worldometers.info/img/flags/mz-flag.gif'],
            ['country_name' => 'Myanmar', 'flag' => 'https://www.worldometers.info/img/flags/bm-flag.gif'],
            ['country_name' => 'Namibia', 'flag' => 'https://www.worldometers.info/img/flags/wa-flag.gif'],
            ['country_name' => 'Nauru', 'flag' => 'https://www.worldometers.info/img/flags/nr-flag.gif'],
            ['country_name' => 'Nepal', 'flag' => 'https://www.worldometers.info/img/flags/np-flag.gif'],
            ['country_name' => 'Netherlands', 'flag' => 'https://www.worldometers.info/img/flags/nl-flag.gif'],
            ['country_name' => 'New Zealand', 'flag' => 'https://www.worldometers.info/img/flags/nz-flag.gif'],
            ['country_name' => 'Nicaragua', 'flag' => 'https://www.worldometers.info/img/flags/nu-flag.gif'],
            ['country_name' => 'Niger', 'flag' => 'https://www.worldometers.info/img/flags/ng-flag.gif'],
            ['country_name' => 'Nigeria', 'flag' => 'https://www.worldometers.info/img/flags/ni-flag.gif'],
            ['country_name' => 'North Macedonia', 'flag' => 'https://www.worldometers.info/img/flags/mk-flag.gif'],
            ['country_name' => 'Norway', 'flag' => 'https://www.worldometers.info/img/flags/no-flag.gif'],
            ['country_name' => 'Oman', 'flag' => 'https://www.worldometers.info/img/flags/mu-flag.gif'],
            ['country_name' => 'Pakistan', 'flag' => 'https://www.worldometers.info/img/flags/pk-flag.gif'],
            ['country_name' => 'Palau', 'flag' => 'https://www.worldometers.info/img/flags/ps-flag.gif'],
            ['country_name' => 'Panama', 'flag' => 'https://www.worldometers.info/img/flags/pm-flag.gif'],
            ['country_name' => 'Papua New Guinea', 'flag' => 'https://www.worldometers.info/img/flags/pp-flag.gif'],
            ['country_name' => 'Paraguay', 'flag' => 'https://www.worldometers.info/img/flags/pa-flag.gif'],
            ['country_name' => 'Peru', 'flag' => 'https://www.worldometers.info/img/flags/pe-flag.gif'],
            ['country_name' => 'Philippines', 'flag' => 'https://www.worldometers.info/img/flags/rp-flag.gif'],
            ['country_name' => 'Poland', 'flag' => 'https://www.worldometers.info/img/flags/pl-flag.gif'],
            ['country_name' => 'Portugal', 'flag' => 'https://www.worldometers.info/img/flags/po-flag.gif'],
            ['country_name' => 'Qatar', 'flag' => 'https://www.worldometers.info/img/flags/qa-flag.gif'],
            ['country_name' => 'Romania', 'flag' => 'https://www.worldometers.info/img/flags/ro-flag.gif'],
            ['country_name' => 'Russia', 'flag' => 'https://www.worldometers.info/img/flags/rs-flag.gif'],
            ['country_name' => 'Rwanda', 'flag' => 'https://www.worldometers.info/img/flags/rw-flag.gif'],
            ['country_name' => 'Saint Lucia', 'flag' => 'https://www.worldometers.info/img/flags/st-flag.gif'],
            ['country_name' => 'Samoa', 'flag' => 'https://www.worldometers.info/img/flags/ws-flag.gif'],
            ['country_name' => 'San Marino', 'flag' => 'https://www.worldometers.info/img/flags/sm-flag.gif'],
            ['country_name' => 'Saudi Arabia', 'flag' => 'https://www.worldometers.info/img/flags/sa-flag.gif'],
            ['country_name' => 'Senegal', 'flag' => 'https://www.worldometers.info/img/flags/sg-flag.gif'],
            ['country_name' => 'Serbia', 'flag' => 'https://www.worldometers.info/img/flags/ri-flag.gif'],
            ['country_name' => 'Seychelles', 'flag' => 'https://www.worldometers.info/img/flags/se-flag.gif'],
            ['country_name' => 'Sierra Leone', 'flag' => 'https://www.worldometers.info/img/flags/sl-flag.gif'],
            ['country_name' => 'Singapore', 'flag' => 'https://www.worldometers.info/img/flags/sn-flag.gif'],
            ['country_name' => 'Slovakia', 'flag' => 'https://www.worldometers.info/img/flags/lo-flag.gif'],
            ['country_name' => 'Slovenia', 'flag' => 'https://www.worldometers.info/img/flags/si-flag.gif'],
            ['country_name' => 'Solomon Islands', 'flag' => 'https://www.worldometers.info/img/flags/bp-flag.gif'],
            ['country_name' => 'Somalia', 'flag' => 'https://www.worldometers.info/img/flags/so-flag.gif'],
            ['country_name' => 'South Africa', 'flag' => 'https://www.worldometers.info/img/flags/sf-flag.gif'],
            ['country_name' => 'South Korea', 'flag' => 'https://www.worldometers.info/img/flags/ks-flag.gif'],
            ['country_name' => 'South Sudan', 'flag' => 'https://www.worldometers.info/img/flags/od-flag.gif'],
            ['country_name' => 'Spain', 'flag' => 'https://www.worldometers.info/img/flags/sp-flag.gif'],
            ['country_name' => 'Sri Lanka', 'flag' => 'https://www.worldometers.info/img/flags/ce-flag.gif'],
            ['country_name' => 'Palestine', 'flag' => 'https://www.worldometers.info/img/flags/palestine-flag.gif'],
            ['country_name' => 'Sudan', 'flag' => 'https://www.worldometers.info/img/flags/su-flag.gif'],
            ['country_name' => 'Suriname', 'flag' => 'https://www.worldometers.info/img/flags/ns-flag.gif'],
            ['country_name' => 'Sweden', 'flag' => 'https://www.worldometers.info/img/flags/sw-flag.gif'],
            ['country_name' => 'Switzerland', 'flag' => 'https://www.worldometers.info/img/flags/sz-flag.gif'],
            ['country_name' => 'Syria', 'flag' => 'https://www.worldometers.info/img/flags/sy-flag.gif'],
            ['country_name' => 'Tajikistan', 'flag' => 'https://www.worldometers.info/img/flags/ti-flag.gif'],
            ['country_name' => 'Tanzania', 'flag' => 'https://www.worldometers.info/img/flags/tz-flag.gif'],
            ['country_name' => 'Thailand', 'flag' => 'https://www.worldometers.info/img/flags/th-flag.gif'],
            ['country_name' => 'Timor-Leste', 'flag' => 'https://www.worldometers.info/img/flags/tt-flag.gif'],
            ['country_name' => 'Togo', 'flag' => 'https://www.worldometers.info/img/flags/to-flag.gif'],
            ['country_name' => 'Tonga', 'flag' => 'https://www.worldometers.info/img/flags/tn-flag.gif'],
            ['country_name' => 'Tunisia', 'flag' => 'https://www.worldometers.info/img/flags/ts-flag.gif'],
            ['country_name' => 'Turkey', 'flag' => 'https://www.worldometers.info/img/flags/tu-flag.gif'],
            ['country_name' => 'Turkmenistan', 'flag' => 'https://www.worldometers.info/img/flags/tx-flag.gif'],
            ['country_name' => 'Tuvalu', 'flag' => 'https://www.worldometers.info/img/flags/tv-flag.gif'],
            ['country_name' => 'U.A.E.', 'flag' => 'https://www.worldometers.info/img/flags/ae-flag.gif'],
            ['country_name' => 'U.K.', 'flag' => 'https://www.worldometers.info/img/flags/uk-flag.gif'],
            ['country_name' => 'U.S.', 'flag' => 'https://www.worldometers.info/img/flags/us-flag.gif'],
            ['country_name' => 'Uganda', 'flag' => 'https://www.worldometers.info/img/flags/ug-flag.gif'],
            ['country_name' => 'Ukraine', 'flag' => 'https://www.worldometers.info/img/flags/up-flag.gif'],
            ['country_name' => 'Uruguay', 'flag' => 'https://www.worldometers.info/img/flags/uy-flag.gif'],
            ['country_name' => 'Uzbekistan', 'flag' => 'https://www.worldometers.info/img/flags/uz-flag.gif'],
            ['country_name' => 'Vanuatu', 'flag' => 'https://www.worldometers.info/img/flags/nh-flag.gif'],
            ['country_name' => 'Venezuela', 'flag' => 'https://www.worldometers.info/img/flags/ve-flag.gif'],
            ['country_name' => 'Vietnam', 'flag' => 'https://www.worldometers.info/img/flags/vm-flag.gif'],
            ['country_name' => 'Yemen', 'flag' => 'https://www.worldometers.info/img/flags/ym-flag.gif'],
            ['country_name' => 'Zambia', 'flag' => 'https://www.worldometers.info/img/flags/za-flag.gif'],
            ['country_name' => 'Zimbabwe', 'flag' => 'https://www.worldometers.info/img/flags/zi-flag.gif'],


           
        ];
        foreach ($countries as $country) {
            CountryFlag::create($country);
        }
    }
}
